version: '3'
networks:
    monitoring:
services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  spotifarm-head:
    image: munchiez/spotifarm
    volumes:
      - "./mopidy.conf:/mopidy.conf"
      - spotifarm-data:/var/lib/mopidy
    restart: always
    user: root
    ports:
      - "6600:6600"
      - "6680:6680"
      - "6681:6681"
    labels:
      - "traefik.frontend.rule=Host:1.spotifarm.local"
      - "traefik.port=6680"
      - "traefik.backend=spotifarm1"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http"
  portainer:
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock --no-auth
    networks:
      - monitoring
    ports:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.spotifarm.local"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_monitoring"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.default.protocol=http"
volumes:
  spotifarm-data:
  portainer-data:
